//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderClient.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AddItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_orderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_itemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_orderId {
            get {
                return this.p_orderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.p_orderIdField, value) != true)) {
                    this.p_orderIdField = value;
                    this.RaisePropertyChanged("p_orderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string p_itemId {
            get {
                return this.p_itemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.p_itemIdField, value) != true)) {
                    this.p_itemIdField = value;
                    this.RaisePropertyChanged("p_itemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IStartOrder")]
    public interface IStartOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStartOrder/StartOrder", ReplyAction="http://tempuri.org/IStartOrder/StartOrderResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="p_orderId")]
        string StartOrder(string p_customerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStartOrder/StartOrder", ReplyAction="http://tempuri.org/IStartOrder/StartOrderResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="p_orderId")]
        System.Threading.Tasks.Task<string> StartOrderAsync(string p_customerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStartOrderChannel : OrderClient.OrderService.IStartOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartOrderClient : System.ServiceModel.ClientBase<OrderClient.OrderService.IStartOrder>, OrderClient.OrderService.IStartOrder {
        
        public StartOrderClient() {
        }
        
        public StartOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StartOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StartOrder(string p_customerName) {
            return base.Channel.StartOrder(p_customerName);
        }
        
        public System.Threading.Tasks.Task<string> StartOrderAsync(string p_customerName) {
            return base.Channel.StartOrderAsync(p_customerName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IAddItem")]
    public interface IAddItem {
        
        // CODEGEN: Generating message contract since the operation AddItem is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddItem/AddItem", ReplyAction="http://tempuri.org/IAddItem/AddItemResponse")]
        OrderClient.OrderService.AddItemResponse AddItem(OrderClient.OrderService.AddItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddItem/AddItem", ReplyAction="http://tempuri.org/IAddItem/AddItemResponse")]
        System.Threading.Tasks.Task<OrderClient.OrderService.AddItemResponse> AddItemAsync(OrderClient.OrderService.AddItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OrderClient.OrderService.AddItem AddItem;
        
        public AddItemRequest() {
        }
        
        public AddItemRequest(OrderClient.OrderService.AddItem AddItem) {
            this.AddItem = AddItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public AddItemResponse() {
        }
        
        public AddItemResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddItemChannel : OrderClient.OrderService.IAddItem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddItemClient : System.ServiceModel.ClientBase<OrderClient.OrderService.IAddItem>, OrderClient.OrderService.IAddItem {
        
        public AddItemClient() {
        }
        
        public AddItemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddItemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddItemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddItemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrderClient.OrderService.AddItemResponse OrderClient.OrderService.IAddItem.AddItem(OrderClient.OrderService.AddItemRequest request) {
            return base.Channel.AddItem(request);
        }
        
        public string AddItem(OrderClient.OrderService.AddItem AddItem1) {
            OrderClient.OrderService.AddItemRequest inValue = new OrderClient.OrderService.AddItemRequest();
            inValue.AddItem = AddItem1;
            OrderClient.OrderService.AddItemResponse retVal = ((OrderClient.OrderService.IAddItem)(this)).AddItem(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrderClient.OrderService.AddItemResponse> OrderClient.OrderService.IAddItem.AddItemAsync(OrderClient.OrderService.AddItemRequest request) {
            return base.Channel.AddItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrderClient.OrderService.AddItemResponse> AddItemAsync(OrderClient.OrderService.AddItem AddItem) {
            OrderClient.OrderService.AddItemRequest inValue = new OrderClient.OrderService.AddItemRequest();
            inValue.AddItem = AddItem;
            return ((OrderClient.OrderService.IAddItem)(this)).AddItemAsync(inValue);
        }
    }
}
