//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.UpperCaseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpperCaseService.IUpperCaseString")]
    public interface IUpperCaseString {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpperCaseString/ReverseString", ReplyAction="http://tempuri.org/IUpperCaseString/ReverseStringResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ModifiedString")]
        string ReverseString(string InputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpperCaseString/ReverseString", ReplyAction="http://tempuri.org/IUpperCaseString/ReverseStringResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ModifiedString")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string InputString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpperCaseStringChannel : Client.UpperCaseService.IUpperCaseString, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpperCaseStringClient : System.ServiceModel.ClientBase<Client.UpperCaseService.IUpperCaseString>, Client.UpperCaseService.IUpperCaseString {
        
        public UpperCaseStringClient() {
        }
        
        public UpperCaseStringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpperCaseStringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpperCaseStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpperCaseStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReverseString(string InputString) {
            return base.Channel.ReverseString(InputString);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string InputString) {
            return base.Channel.ReverseStringAsync(InputString);
        }
    }
}
