//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestedServices.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IReverseString")]
    public interface IReverseString {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReverseString/ReverseString", ReplyAction="http://tempuri.org/IReverseString/ReverseStringResponse")]
        NestedServices.ServiceReference1.ReverseStringResponse ReverseString(NestedServices.ServiceReference1.ReverseStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReverseString/ReverseString", ReplyAction="http://tempuri.org/IReverseString/ReverseStringResponse")]
        System.Threading.Tasks.Task<NestedServices.ServiceReference1.ReverseStringResponse> ReverseStringAsync(NestedServices.ServiceReference1.ReverseStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseString", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InputString;
        
        public ReverseStringRequest() {
        }
        
        public ReverseStringRequest(string InputString) {
            this.InputString = InputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseStringResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ReversedString;
        
        public ReverseStringResponse() {
        }
        
        public ReverseStringResponse(string ReversedString) {
            this.ReversedString = ReversedString;
        }
    }
}
